### ISSUE TITLE
include miniaudio  git in the readme.md

### ISSUE THREAD

**Issue by LeonGamerPS1** [SomeGuyWhoLovesCoding/FNF-PeoteView#2]
![image](https://github.com/user-attachments/assets/1902c0bf-ce6f-4c05-b555-3ea09c0b75ce)
yeah so this screenshot shows theres an error, and 

![image](https://github.com/user-attachments/assets/e3ba41d9-7f45-46b8-9b90-c9edfe1756c3)
this one shows YOU  did not include a away on how to get miniaudio

**Comment by SomeGuyWhoLovesCoding** [comment]
You can just download genkit_miniaudio and you're good

**Comment by SomeGuyWhoLovesCoding** [comment]
Readme updated! Sorry for the minor inconvenience.
